-- ============================================================
-- SCRIPT: ERD simplificat (CREATE + DROP)
-- Entitati: Angajati, Clienti, Comenzi, Produse, Oferte, Evenimente,
--           Sali, Rezervari, Animatori
-- Relatii implementate (tabele asociative):
--   - Planificari_organizatorice (Angajati x Evenimente x Sali)
--   - Comenzi_Angajati (Comenzi x Angajati)
--   - Comenzi_Produse (Comenzi x Produse)
--   - Liste_reduceri (Oferte x Produse)
--   - Evenimente_Produse (Evenimente x Produse)
--   - Colaborari (Evenimente x Animatori)
--   - Participari_evenimente (Clienti x Evenimente)
-- ============================================================

-- =========================
-- DROP (ordine sigura)
-- =========================
DROP TABLE Planificari_organizatorice CASCADE CONSTRAINTS;
DROP TABLE Participari_evenimente CASCADE CONSTRAINTS;
DROP TABLE Colaborari CASCADE CONSTRAINTS;
DROP TABLE Evenimente_Produse CASCADE CONSTRAINTS;
DROP TABLE Liste_reduceri CASCADE CONSTRAINTS;
DROP TABLE Comenzi_Angajati CASCADE CONSTRAINTS;
DROP TABLE Comenzi_Produse CASCADE CONSTRAINTS;

DROP TABLE Rezervari CASCADE CONSTRAINTS;
DROP TABLE Comenzi CASCADE CONSTRAINTS;

DROP TABLE Animatori CASCADE CONSTRAINTS;
DROP TABLE Oferte CASCADE CONSTRAINTS;
DROP TABLE Produse CASCADE CONSTRAINTS;
DROP TABLE Evenimente CASCADE CONSTRAINTS;
DROP TABLE Sali CASCADE CONSTRAINTS;
DROP TABLE Clienti CASCADE CONSTRAINTS;
DROP TABLE Angajati CASCADE CONSTRAINTS;

-- =========================
-- CREATE (entitati baza)
-- =========================

CREATE TABLE Angajati (
    id_angajat      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume            VARCHAR2(50)  NOT NULL,
    prenume         VARCHAR2(50)  NOT NULL,
    functie         VARCHAR2(50)  NOT NULL,
    salariu         NUMBER(10,2)  NOT NULL CHECK (salariu > 0),
    data_angajare   DATE          DEFAULT SYSDATE NOT NULL,
    mail            VARCHAR2(100) NOT NULL
    -- CONSTRAINT uq_angajati_mail UNIQUE (mail)
);

CREATE TABLE Clienti (
    id_client   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume        VARCHAR2(50)  NOT NULL,
    prenume     VARCHAR2(50)  NOT NULL,
    nr_tel      VARCHAR2(15)  NOT NULL,
    mail        VARCHAR2(100) NOT NULL
    -- CONSTRAINT uq_clienti_mail UNIQUE (mail)
);

CREATE TABLE Sali (
    id_sala     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume_sala   VARCHAR2(50) NOT NULL,
    capacitate  NUMBER       NOT NULL CHECK (capacitate > 0)
);

CREATE TABLE Evenimente (
    id_eveniment     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tip_eveniment    VARCHAR2(50) NOT NULL,
    data_eveniment   DATE         NOT NULL,
    numar_persoane   NUMBER       NOT NULL CHECK (numar_persoane > 0)
);

CREATE TABLE Animatori (
    id_animator    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume_animator  VARCHAR2(50) NOT NULL,
    tip_activitate VARCHAR2(50) NOT NULL,
    pret_ora       NUMBER(10,2) NOT NULL CHECK (pret_ora > 0)
);

CREATE TABLE Oferte (
    id_oferta      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount       NUMBER(5,2) NOT NULL CHECK (discount >= 0 AND discount <= 100),
    data_expirare  DATE        NOT NULL
);

CREATE TABLE Produse (
    id_produs        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume_produs      VARCHAR2(50) NOT NULL,
    cantitate        NUMBER       NOT NULL CHECK (cantitate >= 0),
    unitate_masura   VARCHAR2(20) NOT NULL CHECK (unitate_masura IN ('buc', 'portie', 'sticla', 'pahar')),
    pret_unitar      NUMBER(10,2) NOT NULL CHECK (pret_unitar > 0)
);

CREATE TABLE Rezervari (
    id_rezervare     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_rezervare   DATE         NOT NULL,
    ora_rezervare    VARCHAR2(10)  NOT NULL
        CHECK ( REGEXP_LIKE(ora_rezervare, '^([0-1][0-9]|2[0-3]):[0-5][0-9]$') ),
    numar_persoane   NUMBER        NOT NULL CHECK (numar_persoane > 0),
    id_client        NUMBER        NOT NULL,
    id_sala          NUMBER        NOT NULL,
    CONSTRAINT fk_rez_client FOREIGN KEY (id_client) REFERENCES Clienti(id_client),
    CONSTRAINT fk_rez_sala   FOREIGN KEY (id_sala)   REFERENCES Sali(id_sala)
);

CREATE TABLE Comenzi (
    id_comanda     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_comanda   DATE         DEFAULT SYSDATE NOT NULL,
    status         VARCHAR2(50) NOT NULL
        CHECK (status IN ('in redactare', 'plasata', 'in curs de preparare', 'platita', 'anulata')),
    -- pret_total     NUMBER(10,2) NOT NULL CHECK (pret_total >= 0),
    id_client      NUMBER       NOT NULL,
    CONSTRAINT fk_com_client FOREIGN KEY (id_client) REFERENCES Clienti(id_client)
);

-- =========================
-- CREATE (relatii / tabele asociative)
-- =========================

-- Comenzi M:N Produse (o comanda contine produse)
CREATE TABLE Comenzi_Produse (
    id_comanda  NUMBER NOT NULL,
    id_produs   NUMBER NOT NULL,
    cantitate   NUMBER NOT NULL CHECK (cantitate > 0),
    PRIMARY KEY (id_comanda, id_produs),
    CONSTRAINT fk_cp_comanda FOREIGN KEY (id_comanda) REFERENCES Comenzi(id_comanda),
    CONSTRAINT fk_cp_produs  FOREIGN KEY (id_produs)  REFERENCES Produse(id_produs)
);

-- Comenzi M:N Angajati (o comanda este preluata/gestionata de angajati)
CREATE TABLE Comenzi_Angajati (
    id_comanda  NUMBER NOT NULL,
    id_angajat  NUMBER NOT NULL,
    rol         VARCHAR2(30),
    PRIMARY KEY (id_comanda, id_angajat),
    CONSTRAINT fk_ca_comanda FOREIGN KEY (id_comanda) REFERENCES Comenzi(id_comanda),
    CONSTRAINT fk_ca_angajat FOREIGN KEY (id_angajat) REFERENCES Angajati(id_angajat)
);

-- Oferte M:N Produse (produse incluse intr-o oferta)
CREATE TABLE Liste_reduceri (
    id_oferta  NUMBER NOT NULL,
    id_produs  NUMBER NOT NULL,
    PRIMARY KEY (id_oferta, id_produs),
    CONSTRAINT fk_lr_oferta FOREIGN KEY (id_oferta) REFERENCES Oferte(id_oferta),
    CONSTRAINT fk_lr_produs FOREIGN KEY (id_produs) REFERENCES Produse(id_produs)
);

-- Evenimente M:N Produse (produse necesare la un eveniment)
CREATE TABLE Evenimente_Produse (
    id_eveniment NUMBER NOT NULL,
    id_produs    NUMBER NOT NULL,
    cantitate    NUMBER NOT NULL CHECK (cantitate > 0),
    PRIMARY KEY (id_eveniment, id_produs),
    CONSTRAINT fk_ep_eveniment FOREIGN KEY (id_eveniment) REFERENCES Evenimente(id_eveniment),
    CONSTRAINT fk_ep_produs    FOREIGN KEY (id_produs)    REFERENCES Produse(id_produs)
);

-- Evenimente M:N Animatori (colaborari)
CREATE TABLE Colaborari (
    id_eveniment NUMBER NOT NULL,
    id_animator  NUMBER NOT NULL,
    numar_ore NUMBER NOT NULL,
    PRIMARY KEY (id_eveniment, id_animator),
    CONSTRAINT fk_col_eveniment FOREIGN KEY (id_eveniment) REFERENCES Evenimente(id_eveniment),
    CONSTRAINT fk_col_animator  FOREIGN KEY (id_animator)  REFERENCES Animatori(id_animator)
);

-- Clienti M:N Evenimente (participari)
CREATE TABLE Participari_evenimente (
    id_eveniment NUMBER NOT NULL,
    id_client    NUMBER NOT NULL,
    PRIMARY KEY (id_eveniment, id_client),
    CONSTRAINT fk_pe_eveniment FOREIGN KEY (id_eveniment) REFERENCES Evenimente(id_eveniment),
    CONSTRAINT fk_pe_client    FOREIGN KEY (id_client)    REFERENCES Clienti(id_client)
);

-- Relatie ternara: Angajati x Evenimente x Sali (planificari organizatorice)
CREATE TABLE Planificari_organizatorice (
    id_angajat   NUMBER NOT NULL,
    id_eveniment NUMBER NOT NULL,
    id_sala      NUMBER NOT NULL,
    observatii   VARCHAR2(200),
    PRIMARY KEY (id_angajat, id_eveniment, id_sala),
    CONSTRAINT fk_po_angajat   FOREIGN KEY (id_angajat)   REFERENCES Angajati(id_angajat),
    CONSTRAINT fk_po_eveniment FOREIGN KEY (id_eveniment) REFERENCES Evenimente(id_eveniment),
    CONSTRAINT fk_po_sala      FOREIGN KEY (id_sala)      REFERENCES Sali(id_sala)
);
